[project]
name = "pipe-artigo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "psutil>=7.2.1",
    "pyspark>=4.1.1",
]
